services:
  # Frontend service - React web service with SPA routing
  - type: web_service
    name: cst-435-project-hub-frontend
    runtime: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: npx serve -s frontend/build -l 3000

  # Backend service - FastAPI
  - type: web_service
    name: cst-435-project-hub
    env: python311
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    # Expose the port
    port: 8000
